export const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAIL = "GET_ARTICLES_FAIL";

export const GET_ARTICLES_DETAIL_REQUEST = "GET_ARTICLE_DETAIL_REQUEST";
export const GET_ARTICLES_DETAIL_SUCCESS = "GET_ARTICLE_DETAIL_SUCCESS";
export const GET_ARTICLES_DETAIL_FAIL = "GET_ARTICLE_DETAIL_FAIL";
export const GET_ARTICLES_DETAIL_RESET = "GET_ARTICLE_DETAIL_RESET";